force-app/main/default/objects/Batch_Apex_Error__c/Batch_Apex_Error__c.object-meta.xml
<CustomObject>
    <label>Batch Apex Error</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Apex Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <inlineHelpText>The name of the class that triggered the scheduled job</inlineHelpText>
    <label>Apex Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Batch_Phase__c.field-meta.xml
<CustomField>
    <fullName>Batch_Phase__c</fullName>
    <label>Batch Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>START</fullName>
            </value>
            <value>
                <fullName>EXECUTE</fullName>
            </value>
            <value>
                <fullName>FINISH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <inlineHelpText>The AsyncApexJob record for the batch Apex job that failed.</inlineHelpText>
    <label>Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Job_Scope__c.field-meta.xml
<CustomField>
    <fullName>Job_Scope__c</fullName>
    <inlineHelpText>The Record IDs that are in scope if the event was fired from the execute() method of a batch job. If the batch job uses custom iterators instead of sObjects, JobScope is the toString() representation of the iterable objects.</inlineHelpText>
    <label>Job Scope</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Replay_ID__c.field-meta.xml
<CustomField>
    <fullName>Replay_ID__c</fullName>
    <inlineHelpText>Represents an ID value that is populated by the system and refers to the position of the event in the event stream. Replay ID values aren’t guaranteed to be contiguous for consecutive events. A subscriber can store a replay ID value and use it on resubscription to retrieve missed events that are within the retention window.</inlineHelpText>
    <label>Replay ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Apex_Error_Settings__c/Batch_Apex_Error_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Batch Apex Error Handler Settings</label>
</CustomObject>

force-app/main/default/objects/Batch_Apex_Error_Settings__c/fields/Store_Errors_in_Custom_Object__c.field-meta.xml
<CustomField>
    <fullName>Store_Errors_in_Custom_Object__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, records will be stored in the Batch Apex Error object for reporting beyond the 24 hours.</inlineHelpText>
    <label>Store Errors in Custom Object</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchApexErrorEventHandler.cls
public with sharing class BatchApexErrorEventHandler {
    private Map<Id,AsyncApexJob> jobMap;
    private Map<Id,ApexClass> classMap;

    public BatchApexErrorEventHandler(){}

    public void handle(BatchApexErrorEvent[] errorEvents){
        Batch_Apex_Error_Settings__c settings = getSettings();
        getClassInfo(errorEvents);
        if(settings.Store_Errors_in_Custom_Object__c == TRUE){
            copyErrorsToSObject(errorEvents);
        }
    }

    private Batch_Apex_Error_Settings__c getSettings(){
        return Batch_Apex_Error_Settings__c.getInstance();
    }

    private void getClassInfo(BatchApexErrorEvent[] errorEvents){
        Set<Id> jobIds = new Set<Id>();
        for(BatchApexErrorEvent errorEvent: errorEvents){
            jobIds.add(errorEvent.AsyncApexJobId);
        }
        jobMap = new Map<Id,AsyncApexJob>([SELECT Id, ApexClassID FROM AsyncApexJob WHERE Id IN :jobIds]);
        Set<Id> classIds = new Set<Id>();
        for(AsyncApexJob job : jobMap.values()){
            classIds.add(job.ApexClassId);
        }
        classMap = new Map<Id,ApexClass>([SELECT Id, Name FROM ApexClass WHERE Id IN :classIds]);
    }

    private void copyErrorsToSObject(BatchApexErrorEvent[] errorEvents){
        Batch_Apex_Error__c[] errors = new Batch_Apex_Error__c[]{};
        for(BatchApexErrorEvent errorEvent: errorEvents){
            errors.add(new Batch_Apex_Error__c(
                    Apex_Class__c = classMap.get(jobMap.get(errorEvent.AsyncApexJobId).ApexClassId).Name,
                    Job_Id__c = errorEvent.AsyncApexJobId,
                    Batch_Phase__c = errorEvent.Phase,
                    Exception__c = errorEvent.Message,
                    Exception_Type__c = errorEvent.ExceptionType,
                    Job_Scope__c = errorEvent.JobScope,
                    Replay_ID__c = errorEvent.ReplayId,
                    Stack_Trace__c = errorEvent.StackTrace
            ));
        }
        insert errors;
    }
}